### ISSUE TITLE
Add gem to RubyGems

### ISSUE THREAD

**Issue by kajatiger** [pludoni/ba_upload#1]

**Comment by zealot128** [comment]
thx for the interest. I thought the topic is very specific. One can always include the gem via gem 'ba_upload', git: '....'

Do you feel the need for a "full" release?

**Comment by kajatiger** [comment]
Thanks for your quick answer! It works as well with the github source, but from the readme documentation it looks like it is part of RubyGems and then it takes a while to find out, that it isn't. Just for convenience a full release would be nice! Otherwise I would definitely mention the source in the documentation. 
Thanks a lot anyway for the gem. Working with the BA api is not the easiest thing and I was relieved to find the gem with the nice mechanize solution.

**Comment by zealot128** [comment]
I've released ba_upload version 0.1.0!
Thx for the input :)
