### ISSUE TITLE
Type Error when uploading File

### ISSUE THREAD

**Issue by kajatiger** [pludoni/ba_upload#2]
Hello again!

There seems to be some problem with passing a `File` object as an argument in the `upload`  method. I get the error message 
```
TypeError (no implicit conversion of File into String)
```
when calling 
```ruby
connection.upload(file: File.open(xml_path))
```
I will try to dig a bit deeper into the source code of the gem and see if mechanize actually needs a `String` as an argument or something.

**Comment by zealot128** [comment]
Yes. mechanize expects a file path to pass to the form field: 
https://www.rubydoc.info/gems/mechanize/1.0.0/Mechanize/Form/FileUpload


So, just pass the file name: 

```
connection.upload(file: xml_path)
```

It's not possible with mechanize to pass a whole file string/blob.



Our param name could be clearer though, file_name or path... Though it would be a breaking change.

**Comment by kajatiger** [comment]
I tried that already, but then I get a different error:
```
Mechanize::ResponseCodeError (403 => Net::HTTPForbidden for https://hrbaxml.arbeitsagentur.de/in/upload.php -- unhandled response)
```
But I know that the certificate works. I already tried it...

**Comment by zealot128** [comment]
mhm difficult to debug without being able to reproduce.

Maybe it's just a BA server error?
We've also received errors on our daily cronjob this morning:

```
too many connection resets (due to Net::ReadTimeout - Net::ReadTimeout) 
```

We've also did not do any fancy thing:

```ruby
xml = generate_feed
filename = make_name # ... DATA_PATH/"%Y-%m-%d_%H-%M-%S_F ...
File.write(filename,  xml)
upload = BaUpload.open_connection(
  file_path: CERTIFICATE_PATH, passphrase: CERTIFICATE_PASSPHRASE)
ba_connection.upload(file: filename)
```

I just checked, it works now for us.

Some ideas i would start to investigate.

* Make sure the filename matches the strict BA conventions given in the pdf doc.
* Make sure the CERTIFCATE_PATH and the filename are absolute paths from root (File.extend_path)
* Make sure the xml file is generated correctly, has content and is valid xml, maybe it's a Tempfile and already got cleaned up? maybe silent error and the xml file empty
* ... can you upload the same file manually via browser

**Comment by kajatiger** [comment]
Thanks a lot @zealot128 !
I will try to investigate and let you know here. With the pdf doc I guess you mean the "WhitePaper"..? I didn't find anything about the naming convention there. Considering the paths I am generating them from root and they reach the correct files from the console. I also tried to validate the xml against the HRBAXML.xsd, but the files where too big 😅

**Comment by zealot128** [comment]
Yeah about the too big... we are splitting our upload process in several xml documents.
E.g. you could generate one xml for every company that you supply for.

**Comment by zealot128** [comment]
Yes, that whitepaper.
At least the names would be enforced before. Not sure with the latest updates.

Here is a snippet from our make_name:

```ruby
PARTNER_ID = "P0001xxxxx".freeze
FOLDER = "/path/to/data_dir"

now = Time.zone.now
index = 0
total_count =User.with_jobs.count
User.with_jobs.find_each do |user|
  index += 1
  name = make_name(index, total_count)

  ... upload(filename)
end

# index would be the number of the user, e.g. User....with_index(user, i) 
def make_name(index)
     ended = index == (@user_count - 1)
      flag = ended ? "E" : "C"
      date = @now.strftime "%Y-%m-%d_%H-%M-%S_F#{'%03d' % (index + 1)}#{flag}"
      "#{FOLDER}/DS#{PARTNER_ID}_#{date}.xml"
end
```
Notes:

* Filename must end with C or E, E would be the last in a Batch - Not sure if this is still used though. This was relict from the "API" of BA before ... which was a propriatary FTP tool (connectftp).

have fun ;)

**Comment by kajatiger** [comment]
Awesome! Make sure to drop by the Absolventa office when you are in Berlin. There's free beers/coffee/else waiting.

**Comment by zealot128** [comment]
Thanks :)

Happy to see other jobboards also using Rails!
If you got successful, feel free to add any gained knowledge missing in the README!

**Comment by kajatiger** [comment]
Since the upload worked and there was no error within the gem, I will happily close this issue. Chapeau for your work!
